UPDATE users SET role = 'OPERATOR' WHERE role = 'USER';

ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_users_role;
ALTER TABLE users ALTER COLUMN role SET DEFAULT 'VIEWER';
ALTER TABLE users
    ADD CONSTRAINT chk_users_role CHECK (role IN ('ADMIN', 'OPERATOR', 'APPROVER', 'VIEWER'));
