apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forgeops
  namespace: forgeops
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "130"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - forgeops.example.com
      secretName: forgeops-tls
  rules:
    - host: forgeops.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
